Update Golang to `1.23.0` (#16599)
Signed-off-by: Florent Poinsard <florent.poinsard@outlook.fr>
Signed-off-by: Andres Taylor <andres@planetscale.com>
Co-authored-by: Andres Taylor <andres@planetscale.com>

diff --git a/misc/git/hooks/golangci-lint b/misc/git/hooks/golangci-lint
--- a/misc/git/hooks/golangci-lint
+++ b/misc/git/hooks/golangci-lint
@@ -13,18 +13,32 @@
 # See the License for the specific language governing permissions and
 # limitations under the License.
 
-GOLANGCI_LINT=$(command -v golangci-lint >/dev/null 2>&1)
-if [ $? -eq 1 ]; then
-  echo "Downloading golangci-lint..."
-  go install github.com/golangci/golangci-lint/cmd/golangci-lint@v1.56.2
+# Required version of golangci-lint
+REQUIRED_VERSION="v1.60.1"
+
+# Check if golangci-lint is installed and capture the version
+if ! command -v golangci-lint >/dev/null 2>&1; then
+  echo "golangci-lint not found. Installing version $REQUIRED_VERSION..."
+  go install github.com/golangci/golangci-lint/cmd/golangci-lint@$REQUIRED_VERSION
+else
+  VERSION_OUTPUT=$(golangci-lint --version)
+  INSTALLED_VERSION=$(echo "$VERSION_OUTPUT" | sed -n 's/^golangci-lint has version \([v0-9.]*\).*/\1/p')
+  if [ "$INSTALLED_VERSION" != "$REQUIRED_VERSION" ]; then
+    echo "golangci-lint version $INSTALLED_VERSION found, but $REQUIRED_VERSION is required."
+    echo "Installing correct version $REQUIRED_VERSION..."
+    go install github.com/golangci/golangci-lint/cmd/golangci-lint@$REQUIRED_VERSION
+  fi
 fi
 
+# Get list of Go files to lint
 gofiles=$(git diff --cached --name-only --diff-filter=ACM | grep '^go/.*\.go$')
 if [ -z "$gofiles" ]; then
   exit 0
 fi
 
+# Get unique directories of the Go files
 gopackages=$(echo "$gofiles" | xargs -n1 dirname | sort -u | paste -sd ' ' -)
 
+# Lint the Go packages
 echo "Linting $gopackages"
 golangci-lint run $gopackages
