Print command to install golint if it's not found.

diff --git a/misc/git/hooks/golint b/misc/git/hooks/golint
--- a/misc/git/hooks/golint
+++ b/misc/git/hooks/golint
@@ -9,6 +9,12 @@
 # it has execute permissions.
 #
 # This script does not handle file names that contain spaces.
+
+if [ -z "$(which golint)" ]; then
+  echo "golint not found, please run: go get github.com/golang/lint/golint"
+  exit 1
+fi
+
 gofiles=$(git diff --cached --name-only --diff-filter=ACM | grep '.go$')
 
 errors=
