functional setup
Signed-off-by: Shlomi Noach <2607934+shlomi-noach@users.noreply.github.com>

diff --git a/docker/mini/docker-entry b/docker/mini/docker-entry
--- a/docker/mini/docker-entry
+++ b/docker/mini/docker-entry
@@ -18,7 +18,7 @@
 #
 
 echo_sleep() {
-  SECONDS="$1"
+  local SECONDS="$1"
   for i in $(seq 1 $SECONDS) ; do 
     echo -n "."
     sleep 1
@@ -26,72 +26,107 @@ echo_sleep() {
   echo
 }
 
+echo_header() {
+  local HEADER="$1"
+  echo ""
+  echo "# $HEADER"
+}
+
 SCRIPTS_PATH="/vt/dist/scripts"
 export CELL=${CELL:-zone1}
 export $TOPOLOGY_USER
 export $TOPOLOGY_PASSWORD
 
-echo "############################################################"
-echo "vitess self resolve cluster"
-echo "############################################################"
 
-if [ -z  "$MYSQL_SCHEMA" ] ; then
+cat <<- "EOF"
+=============================================
+
+|  \/  (_)_ __ (_) \   / (_) |_ ___  ___ ___ 
+| |\/| | | '_ \| |\ \ / /| | __/ _ \/ __/ __|
+| |  | | | | | | | \ V / | | ||  __/\__ \__ \
+|_|  |_|_|_| |_|_|  \_/  |_|\__\___||___/___/
+
+=============================================
+EOF
+
+if [ -z "$MYSQL_SCHEMA" ] ; then
   echo "Expected MYSQL_SCHEMA environment variable"
   exit 1
 fi
+if [ -z "$TOPOLOGY_SERVER" ] ; then
+  echo "TOPOLOGY_SERVER environment variable not found. You must specify a MySQL server within your topology."
+  echo "This mini-vitess setup will attempt to discover your topology using that server and will bootstrap to match your topology"
+  exit 1
+fi
+if [ -z "$TOPOLOGY_USER" ] ; then
+  echo "TOPOLOGY_USER environment variable not found. You must specify a MySQL username accessible to vitess."
+  exit 1
+fi
+if [ -z "$TOPOLOGY_PASSWORD" ] ; then
+  echo "TOPOLOGY_PASSWORD environment variable not found. You must specify a MySQL password accessible to vitess."
+  exit 1
+fi
+
+echo "MiniVitess is starting up..."
+echo "- Given MySQL topology server: $TOPOLOGY_SERVER"
+echo "- Given MySQL schema: $MYSQL_SCHEMA"
 
 cd $SCRIPTS_PATH
 
-. ./env.sh
+source ./env.sh
 
+echo_header "orchestrator"
 ./orchestrator-up.sh
+echo "- orchestrator will meanwhile probe and map your MySQL replication topology"
 
+echo_header "etcd"
 ./etcd-up.sh
 
-# start vtctld
-./vtctld-up.sh
+echo_header "vtctld"
+./vtctld-mini-up.sh
 
-./vtgate-up.sh
+echo_header "Waiting for topology to be detected and analyzed"
+echo_sleep 15
 
-echo "Waiting gracefully for topology to be detected and analyzed"
-echo_sleep 5
-
-echo "vitess/orchestrator have detected the following MySQL servers:"
+echo_header "orchestrator has detected the following MySQL servers:"
 orchestrator-client -c all-instances
+
+echo_header "Bootstrapping vttablets for the above instances..."
 
 BASE_TABLET_UID=100
 for i in $(orchestrator-client -c all-instances) ; do
   read -r mysql_host mysql_port <<<$(echo $i | tr ':' ' ') 
-  # TABLET_UID=$BASE_TABLET_UID ./scripts/mysqlctl-up.sh
-  tablet_port=$[15000 + $BASE_TABLET_UID]
 
-	KEYSPACE=$MYSQL_SCHEMA TABLET_UID=$BASE_TABLET_UID ./vttablet-mini-up.sh $mysql_host $mysql_port $tablet_port
-  echo "+ vttablet started"
-  tablet_alias="$(curl -s http://$(hostname):${tablet_port}/debug/vars | jq -r '.TabletAlias')"
+  is_master=""
   if [ "$i" == "$(orchestrator-client -c which-cluster-master -i "$i")" ] ; then
-    echo "setting vttablet as master"
-    echo vtctlclient -server "$(hostname):$vtctld_web_port" InitShardMaster -force "${MYSQL_SCHEMA}/0" "$tablet_alias"
-    echo "+ done"
+    is_master="true"
   fi
+
+	KEYSPACE=$MYSQL_SCHEMA TABLET_UID=$BASE_TABLET_UID ./vttablet-mini-up.sh "$mysql_host" "$mysql_port" "$is_master"
   BASE_TABLET_UID=$((BASE_TABLET_UID + 1))
 done
 
+echo_header "vtgate"
+./vtgate-up.sh
 
-exit
-# start vttablets for keyspace commerce
-for i in 100 101 102; do
-	CELL=zone1 TABLET_UID=$i ./scripts/mysqlctl-up.sh
-	CELL=zone1 KEYSPACE=commerce TABLET_UID=$i ./scripts/vttablet-up.sh
-done
+echo_header "Setup complete"
 
-# set one of the replicas to master
-vtctlclient InitShardMaster -force commerce/0 zone1-100
+echo_header "Your topology is:"
+orchestrator-client -c topology-tabulated -i ${TOPOLOGY_SERVER} | tr '|' ' '
 
-# create the schema
-vtctlclient ApplySchema -sql-file create_commerce_schema.sql commerce
+echo_header "vtgate is listening for MySQL connection on port 15306"
 
-# create the vschema
-vtctlclient ApplyVSchema -vschema_file vschema_commerce_initial.json commerce
+echo_header "On this container, try running any of the following commands:"
+echo "  mysql ${MYSQL_SCHEMA} -e 'show tables'"
+echo "  mysql ${MYSQL_SCHEMA}@master -e 'select @@hostname, @@port'"
+echo "  mysql ${MYSQL_SCHEMA}@replica -e 'select @@hostname, @@port'"
 
-# start vtgate
-CELL=zone1 ./scripts/vtgate-up.sh
+echo_header "Outside this container, try running any of the following commands:"
+echo "  mysql -h $(hostname) --port=15306 ${MYSQL_SCHEMA} -e 'show tables'"
+echo "  mysql -h $(hostname) --port=15306 ${MYSQL_SCHEMA}@master -e 'select @@hostname, @@port'"
+echo "  mysql -h $(hostname) --port=15306 ${MYSQL_SCHEMA}@replica -e 'select @@hostname, @@port'"
+
+echo_header "Ready"
+
+echo ""
+
