Fix mariadb102 and mariadb103 tests on release-12.0 (#11025)
* move all tests out of the self-hosted runners

Signed-off-by: Manan Gupta <manan@planetscale.com>
Signed-off-by: deepthi <deepthi@planetscale.com>

* CI: get mariadb 10.3 from rackspace mirror instead of DO (#11015)

Signed-off-by: deepthi <deepthi@planetscale.com>

Signed-off-by: deepthi <deepthi@planetscale.com>

* CI: add back mariadb102 after cherry-pick, regenerate all workflows

Signed-off-by: deepthi <deepthi@planetscale.com>

Signed-off-by: Manan Gupta <manan@planetscale.com>
Signed-off-by: deepthi <deepthi@planetscale.com>
Co-authored-by: Manan Gupta <manan@planetscale.com>

diff --git a/.github/workflows/unit_test_mysql57.yml b/.github/workflows/unit_test_mysql57.yml
--- a/.github/workflows/unit_test_mysql57.yml
+++ b/.github/workflows/unit_test_mysql57.yml
@@ -8,33 +8,47 @@ concurrency:
 
 jobs:
   test:
-    runs-on: self-hosted
+    runs-on: ubuntu-18.04
 
     steps:
-      - name: Check out code
-        uses: actions/checkout@v2
+    - name: Set up Go
+      uses: actions/setup-go@v2
+      with:
+        go-version: 1.17.12
 
-      - name: Build Docker Image
-        run: docker build -f ./.github/docker/unit_test_mysql57/Dockerfile -t unit_test_mysql57:$GITHUB_SHA  .
+    - name: Tune the OS
+      run: |
+        echo '1024 65535' | sudo tee -a /proc/sys/net/ipv4/ip_local_port_range
 
-      - name: Run test
-        timeout-minutes: 30
-        run: docker run --name "unit_test_mysql57_$GITHUB_SHA" unit_test_mysql57:$GITHUB_SHA /bin/bash -c 'make unit_test'
+    - name: Check out code
+      uses: actions/checkout@v2
 
-      - name: Print Volume Used
-        if: ${{ always() }}
-        run: |
-          docker inspect -f '{{ (index .Mounts 0).Name }}' unit_test_mysql57_$GITHUB_SHA
+    - name: Get dependencies
+      run: |
+        export DEBIAN_FRONTEND="noninteractive"
+        sudo apt-get update
 
-      - name: Cleanup Docker Volume
-        run: |
-          docker rm -v unit_test_mysql57_$GITHUB_SHA
+        # mysql57
+        sudo apt-get install -y mysql-server mysql-client
 
-      - name: Cleanup Docker Container
-        if: ${{ always() }}
-        run: |
-          docker rm -f unit_test_mysql57_$GITHUB_SHA
+        sudo apt-get install -y make unzip g++ curl git wget ant openjdk-8-jdk eatmydata
+        sudo service mysql stop
+        sudo bash -c "echo '/usr/sbin/mysqld { }' > /etc/apparmor.d/usr.sbin.mysqld" # https://bugs.launchpad.net/ubuntu/+source/mariadb-10.1/+bug/1806263
+        sudo ln -s /etc/apparmor.d/usr.sbin.mysqld /etc/apparmor.d/disable/
+        sudo apparmor_parser -R /etc/apparmor.d/usr.sbin.mysqld || echo "could not remove mysqld profile"
 
-      - name: Cleanup Docker Image
-        run: |
-          docker image rm unit_test_mysql57:$GITHUB_SHA
+        mkdir -p dist bin
+        curl -L https://github.com/coreos/etcd/releases/download/v3.3.10/etcd-v3.3.10-linux-amd64.tar.gz | tar -zxC dist
+        mv dist/etcd-v3.3.10-linux-amd64/{etcd,etcdctl} bin/
+
+        go mod download
+        go install golang.org/x/tools/cmd/goimports@latest
+
+    - name: Run make tools
+      run: |
+        make tools
+
+    - name: Run test
+      timeout-minutes: 30
+      run: |
+        eatmydata -- make unit_test
