percona sql arm64 fix
Signed-off-by: <ranichowdary.mandepudi@arm.com>

diff --git a/.github/workflows/upgrade_downgrade_test_reparent_old_vtctl.yml b/.github/workflows/upgrade_downgrade_test_reparent_old_vtctl.yml
--- a/.github/workflows/upgrade_downgrade_test_reparent_old_vtctl.yml
+++ b/.github/workflows/upgrade_downgrade_test_reparent_old_vtctl.yml
@@ -116,6 +116,9 @@ jobs:
           sudo dpkg -i libssl1.1_1.1.1f-1ubuntu2.16_arm64.deb libaio1_0.3.112-5_arm64.deb
           sudo dpkg -i mysql-server_8.0.35_arm64.deb
           export PATH=$PATH:/usr/local/mysql/bin
+          echo "VT_MYSQL_ROOT=/usr/local/mysql" >> $GITHUB_ENV
+
+
         else
             sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys A8D3785C
             wget -c https://dev.mysql.com/get/mysql-apt-config_0.8.33-1_all.deb
@@ -127,8 +130,8 @@ jobs:
         # Install everything else we need, and configure
         sudo apt-get install -y make unzip g++ etcd-client etcd-server curl git wget eatmydata
         
-        sudo service mysql stop
-        sudo service etcd stop
+        sudo service mysql stop || echo "mysql stop skipped (service not found)"
+        sudo service etcd stop || echo "etcd stop skipped (service not found)"
         sudo bash -c "echo '/usr/sbin/mysqld { }' > /etc/apparmor.d/usr.sbin.mysqld" # https://bugs.launchpad.net/ubuntu/+source/mariadb-10.1/+bug/1806263
         sudo ln -s /etc/apparmor.d/usr.sbin.mysqld /etc/apparmor.d/disable/
         sudo apparmor_parser -R /etc/apparmor.d/usr.sbin.mysqld || echo "could not remove mysqld profile"
