feat: simplified the manual end-to-end backup test
Signed-off-by: Florent Poinsard <florent.poinsard@outlook.fr>

diff --git a/.github/workflows/upgrade_downgrade_test_backups_manual.yml b/.github/workflows/upgrade_downgrade_test_backups_manual.yml
--- a/.github/workflows/upgrade_downgrade_test_backups_manual.yml
+++ b/.github/workflows/upgrade_downgrade_test_backups_manual.yml
@@ -50,7 +50,7 @@ jobs:
 
   upgrade_downgrade_test:
     if: always() && (github.event_name != 'pull_request' || needs.get_upgrade_downgrade_label.outputs.hasLabel != 'false')
-    name: Run Upgrade Downgrade Test
+    name: Run Upgrade Downgrade Test Backup Manual
     runs-on: ubuntu-latest
     needs:
       - get_upgrade_downgrade_label
@@ -74,13 +74,28 @@ jobs:
 
     - name: Get base dependencies
       run: |
+        sudo DEBIAN_FRONTEND="noninteractive" apt-get update
+        # Uninstall any previously installed MySQL first
+        sudo systemctl stop apparmor
+        sudo DEBIAN_FRONTEND="noninteractive" apt-get remove -y --purge mysql-server mysql-client mysql-common
+        sudo apt-get -y autoremove
+        sudo apt-get -y autoclean
+        sudo deluser mysql
+        sudo rm -rf /var/lib/mysql
+        sudo rm -rf /etc/mysql
+        # Install mysql80
+        wget -c https://dev.mysql.com/get/mysql-apt-config_0.8.20-1_all.deb
+        echo mysql-apt-config mysql-apt-config/select-server select mysql-8.0 | sudo debconf-set-selections
+        sudo DEBIAN_FRONTEND="noninteractive" dpkg -i mysql-apt-config*
         sudo apt-get update
-        sudo apt-get install -y mysql-server mysql-client make unzip g++ etcd curl git wget eatmydata
+        sudo DEBIAN_FRONTEND="noninteractive" apt-get install -y mysql-server mysql-client
+        # Install everything else we need, and configure
+        sudo apt-get install -y make unzip g++ etcd curl git wget eatmydata
         sudo service mysql stop
         sudo service etcd stop
+        sudo bash -c "echo '/usr/sbin/mysqld { }' > /etc/apparmor.d/usr.sbin.mysqld" # https://bugs.launchpad.net/ubuntu/+source/mariadb-10.1/+bug/1806263
         sudo ln -s /etc/apparmor.d/usr.sbin.mysqld /etc/apparmor.d/disable/
-        sudo apparmor_parser -R /etc/apparmor.d/usr.sbin.mysqld
-        go mod download
+        sudo apparmor_parser -R /etc/apparmor.d/usr.sbin.mysqld || echo "could not remove mysqld profile"
 
         # install JUnit report formatter
         go get -u github.com/vitessio/go-junit-report@HEAD
@@ -92,7 +107,7 @@ jobs:
         sudo apt-get install percona-xtrabackup-24
 
     # Checkout to the last release of Vitess
-    - name: Check out other version's code (${{ matrix.project }})
+    - name: Checkout to the other version's code (${{ matrix.project }})
       uses: actions/checkout@v2
       with:
         ref: ${{ matrix.project }}
@@ -111,7 +126,7 @@ jobs:
         rm -Rf bin/*
 
     # Checkout to this build's commit
-    - name: Check out commit's code
+    - name: Checkout to commit's code
       uses: actions/checkout@v2
 
     - name: Get dependencies for this commit
@@ -126,45 +141,19 @@ jobs:
         mkdir -p /tmp/vitess-build-current/
         cp -R bin /tmp/vitess-build-current/
 
-    - name: Create the cluster with VTTablet N
+    - name: Create the example Vitess cluster with all components using version N
       run: |
-        source build.env
         cd examples/local
-        source ./env.sh
-        ./101_initial_cluster.sh
-        sleep 5
-        mysql < ../common/insert_commerce_data.sql
-        ./201_customer_tablets.sh
-        sleep 5
-        ./202_move_tables.sh
-        sleep 3
-        ./203_switch_reads.sh
-        ./204_switch_writes.sh
-        ./205_clean_commerce.sh
-        ./301_customer_sharded.sh
-        ./302_new_shards.sh
-        sleep 5
-        ./303_reshard.sh
-        sleep 3
-        ./304_switch_reads.sh
-        ./305_switch_writes.sh
-        sleep 5
+        ./backups/start_cluster.sh
 
     - name: Take a backup of all the shards
       run: |
-        source build.env
         cd examples/local
-        source ./env.sh
-
-        vtctlclient BackupShard -allow_primary=true customer/-80
-        vtctlclient BackupShard -allow_primary=true customer/80-
-        vtctlclient BackupShard -allow_primary=true commerce/0
+        ./backups/take_backups.sh
 
     - name: Insert more data after the backup
       run: |
-        source build.env
-        cd examples/local
-        source ./env.sh
+        source build.env ; cd examples/local ; source ./env.sh
 
         echo "insert into customer(email) values('new_user_1@domain.com');" | mysql
         echo "insert into product(sku, description, price) values('SKU-1009', 'description', 89);" | mysql
@@ -172,24 +161,8 @@ jobs:
 
     - name: Stop tablets
       run: |
-        source build.env
         cd examples/local
-        source ./env.sh
-
-        for tablet in 100 200 300 400; do
-        	if vtctlclient -action_timeout 1s -server localhost:15999 GetTablet zone1-$tablet >/dev/null 2>&1; then
-        		# The zero tablet is up. Try to shutdown 0-2 tablet + mysqlctl
-        		for i in 0 1 2; do
-        			uid=$(($tablet + $i))
-        			echo "Shutting down tablet zone1-$uid"
-        			CELL=zone1 TABLET_UID=$uid ./scripts/vttablet-down.sh
-        			echo "Shutting down mysql zone1-$uid"
-        			CELL=zone1 TABLET_UID=$uid ./scripts/mysqlctl-down.sh
-        			vtctlclient DeleteTablet -allow_primary=true zone1-$uid
-        			rm -Rf vtdataroot/vt_0000000$uid
-        		done
-        	fi
-        done
+        ./backups/stop_tablets.sh
 
     - name: Use VTTablet N-1
       run: |
@@ -201,36 +174,12 @@ jobs:
 
     - name: Start new tablets using version n-1 and restoring old backup made on version n
       run: |
-        source build.env
         cd examples/local
-        source ./env.sh
-
-        for i in 100 101 102; do
-        	CELL=zone1 TABLET_UID=$i ./scripts/mysqlctl-up.sh
-        	CELL=zone1 KEYSPACE=commerce TABLET_UID=$i ./scripts/vttablet-up.sh
-        done
-        sleep 5
-        vtctldclient InitShardPrimary --force commerce/0 zone1-100
-
-        for i in 300 301 302; do
-        	CELL=zone1 TABLET_UID=$i ./scripts/mysqlctl-up.sh
-        	SHARD=-80 CELL=zone1 KEYSPACE=customer TABLET_UID=$i ./scripts/vttablet-up.sh
-        done
-        sleep 5
-        vtctldclient InitShardPrimary --force customer/-80 zone1-300
-
-        for i in 400 401 402; do
-        	CELL=zone1 TABLET_UID=$i ./scripts/mysqlctl-up.sh
-        	SHARD=80- CELL=zone1 KEYSPACE=customer TABLET_UID=$i ./scripts/vttablet-up.sh
-        done
-        sleep 5
-        vtctldclient InitShardPrimary --force customer/80- zone1-400
+        ./backups/restart_tablets.sh
 
     - name: Query the new tablets to make sure the data has been restored
       run: |
-        source build.env
-        cd examples/local
-        source ./env.sh
+        source build.env ; cd examples/local ; source ./env.sh
 
         echo "select count(sku) from product;" | mysql | grep 2
         echo "select count(email) from customer;" | mysql | grep 5
@@ -238,9 +187,7 @@ jobs:
 
     - name: Insert more data before the backup
       run: |
-        source build.env
-        cd examples/local
-        source ./env.sh
+        source build.env ; cd examples/local ; source ./env.sh
 
         echo "insert into customer(email) values('new_user_2@domain.com');" | mysql
         echo "insert into product(sku, description, price) values('SKU-1011', 'description', 111);" | mysql
@@ -248,34 +195,13 @@ jobs:
 
     - name: Take a second backup of all the shards
       run: |
-        source build.env
         cd examples/local
-        source ./env.sh
-
-        vtctlclient BackupShard -allow_primary=true customer/-80
-        vtctlclient BackupShard -allow_primary=true customer/80-
-        vtctlclient BackupShard -allow_primary=true commerce/0
+        ./backups/take_backups.sh
 
     - name: Stop tablets
       run: |
-        source build.env
         cd examples/local
-        source ./env.sh
-
-        for tablet in 100 200 300 400; do
-        	if vtctlclient -action_timeout 1s -server localhost:15999 GetTablet zone1-$tablet >/dev/null 2>&1; then
-        		# The zero tablet is up. Try to shutdown 0-2 tablet + mysqlctl
-        		for i in 0 1 2; do
-        			uid=$(($tablet + $i))
-        			echo "Shutting down tablet zone1-$uid"
-        			CELL=zone1 TABLET_UID=$uid ./scripts/vttablet-down.sh
-        			echo "Shutting down mysql zone1-$uid"
-        			CELL=zone1 TABLET_UID=$uid ./scripts/mysqlctl-down.sh
-        			vtctlclient DeleteTablet -allow_primary=true zone1-$uid
-        			rm -Rf vtdataroot/vt_0000000$uid
-        		done
-        	fi
-        done
+        ./backups/stop_tablets.sh
 
     - name: Use current version VTTablet, and other version VTBackup
       run: |
@@ -287,36 +213,12 @@ jobs:
 
     - name: Start new tablets using version n and restoring old backup made on version n-1
       run: |
-        source build.env
         cd examples/local
-        source ./env.sh
-
-        for i in 100 101 102; do
-        	CELL=zone1 TABLET_UID=$i ./scripts/mysqlctl-up.sh
-        	CELL=zone1 KEYSPACE=commerce TABLET_UID=$i ./scripts/vttablet-up.sh
-        done
-        sleep 5
-        vtctldclient InitShardPrimary --force commerce/0 zone1-100
-
-        for i in 300 301 302; do
-        	CELL=zone1 TABLET_UID=$i ./scripts/mysqlctl-up.sh
-        	SHARD=-80 CELL=zone1 KEYSPACE=customer TABLET_UID=$i ./scripts/vttablet-up.sh
-        done
-        sleep 5
-        vtctldclient InitShardPrimary --force customer/-80 zone1-300
-
-        for i in 400 401 402; do
-        	CELL=zone1 TABLET_UID=$i ./scripts/mysqlctl-up.sh
-        	SHARD=80- CELL=zone1 KEYSPACE=customer TABLET_UID=$i ./scripts/vttablet-up.sh
-        done
-        sleep 5
-        vtctldclient InitShardPrimary --force customer/80- zone1-400
+        ./backups/restart_tablets.sh
 
     - name: Query the new tablets to make sure the data has been restored
       run: |
-        source build.env
-        cd examples/local
-        source ./env.sh
+        source build.env ; cd examples/local ; source ./env.sh
 
         echo "select count(sku) from product;" | mysql | grep 3
         echo "select count(email) from customer;" | mysql | grep 6
